# version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  web:
    build: ./web
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  api_plans:
    build: ./API_plans
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    restart: unless-stopped

  api_rag:
    build: ./API_rag
    env_file: .env
    volumes:
      - ./gold_doc.txt:/app/gold_doc.txt:ro
    ports:
      - "8002:8002"
    restart: unless-stopped

volumes:
  db_data: